externalPostgresql:
    password: ENC[AES256_GCM,data:brIKZsQ9I26lhH57nAenKw==,iv:awaQZImxvGhNHML8f8cyapa/S2H8GkGx5jmn+D5IoIk=,tag:bsTWMgzPg9gpKW8+qu8/kg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:1111111111111:key/a3d17fd9-83bd-4bad-89b0-6b4b40fe8ba9
          created_at: "2023-02-20T12:42:03Z"
          enc: AQICAHgBj8IQz1ZXwdLKnx3yekxaisb1TMJ/LY9/B6dwVLIR2wFZdZYFkBrLKOy3TUyO81gWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBn1I9KIF6u1PKk3OAgEQgDv++yR9k8SvsNkNSNMod/ZPBLD/2aJb1KXICae262xmNw+8XuWwiSv719pwpm5SBJpxk4HnH6NLLZFkkw==
          aws_profile: bilenkis-staging
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-21T14:38:00Z"
    mac: ENC[AES256_GCM,data:WAsKwe86I1yCO/UjSxXZHPV1VAj5xMyj1Mtu4HEhCuOQjOQ+20cUuY7veka33kM6nilgG/iamT87z8lg/c8orRAmlGGvjeTob9XOjlXID08+qCuyF/G60UQfLkxouGdeK3rZNxEBpr7GUEwB6T68Gx6a6BgbAoc3shLk/TXMR04=,iv:He/q+Y8rFWQJeSTi8iCMTLmPvy6OMhBdJCeBsQPA9+Q=,tag:OkCttvp5lEPuOESWhGKeug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.2
